name: migrate_dev

on: workflow_dispatch

permissions:
  actions: read
  contents: read
jobs:
  deploy-applications:
    name: Deploy Applications with Nx
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.7.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - name: Run database migrations
        # run: pnpm exec nx affected -t migrate-run --base=${{ github.event.before }} --head=${{ github.event.after }} --skip-nx-cache
        run: pnpm exec nx run-many -t migrate:run --skip-nx-cache
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          #   Need to update in secrets after main infrastructure is deployed(@todo fix it)
          DB_HOST: ${{ secrets.DB_HOST }}
